### ISSUE TITLE
re-targeted model disappears when the file is re-opened. 

### ISSUE THREAD

**Issue by vonshavingcream** [anasrar/ReNim#9] opened 2021-03-03 07:57 UTC
I brought the re-target rig into another blender file. made adjustments for it to fit the scene and then saved the file. when I reopen the file the rigify rig and it's meshes doesn't display.   [``](https://imgur.com/a/2r1Dj7M)

[``](https://drive.google.com/file/d/12eKQEZObidzGx0YDsCj9AYmjYtlbIPno/view?usp=sharing)

**Comment by anasrar** [comment] 2021-03-03 11:05
the problem is something about driver and scaling.
it possible because you link/append the rig without unbind.

i see some constraint not fully removed :
![image](https://user-images.githubusercontent.com/38805204/109795712-9c882100-7c5a-11eb-9ed7-8b84ce6efa5d.png)

the things you should do is :
- bind
- bake to action
- unbind
- link/append rig and the action you just bake to another blend file

your mesh still there
![image](https://user-images.githubusercontent.com/38805204/109794593-58485100-7c59-11eb-8b6f-4f88cba01a83.png)
![image](https://user-images.githubusercontent.com/38805204/109796203-3354dd80-7c5b-11eb-939c-90ef2fa0981d.png)

with this lack of information i will recommend to regenerate the rigify rig

**Comment by anasrar** [comment] 2021-03-09 00:32
no further response, I will close this issue in the near future

**Comment by vonshavingcream** [comment] 2021-03-09 14:08
I figured it out. I was not protecting the nodes with a fake user after I copied and pasted the rigs. so when I reopened the files they were gone. After protecting the nodes, everything is working fine.

**Closed as completed** 2021-03-09 17:10 UTC
